openapi: 3.0.0
info:
  title: Budget Tracking API
  description: API for managing user profiles and expenses for budget tracking.
  version: 1.0.0

servers:
  - url: https://your-budget-tracking-api.example.com
    description: Production Server

paths:
  /user/profile:
    get:
      summary: Retrieve User Profile
      description: Get details of the authenticated user's profile.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message.

  /user/expenses:
    get:
      summary: Retrieve User Expenses
      description: Get a list of expenses for the authenticated user.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExpenseList'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message.

components:
  schemas:
    UserProfile:
      type: object
      properties:
        userId:
          type: string
          description: Unique identifier for the user.
        firstName:
          type: string
          description: User's first name.
        lastName:
          type: string
          description: User's last name.
        email:
          type: string
          format: email
          description: User's email address.

    Expense:
      type: object
      properties:
        expenseId:
          type: string
          description: Unique identifier for the expense.
        date:
          type: string
          format: date
          description: Date of the expense.
        amount:
          type: number
          format: float
          description: Expense amount.
        description:
          type: string
          description: Expense description.

    ExpenseList:
      type: array
      items:
        $ref: '#/components/schemas/Expense'


  Error:
    type: object
    properties:
      message:
        type: string
        description: Error message.
